<!DOCTYPE html><html class="no-js" lang="pt-br">
<head> 
<title>ProjectoAW</title> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1"> 
<meta name='author' content='HEBOI' /> <meta name='description' content='Vendas' /> 
<meta name='keywords' content='Vendas_produto' /> <meta property='og:image' content='view/assets/img/logo.png' /> 
<meta property='og:title' content=Vendas /> <meta property='og:description' content='Vendas_produtoFazenda' /> 
<base href="<?= $GLOBALS['referer'] ?>"> <link rel="apple-touch-icon" href="icon.png"> 
<link rel="manifest" href="site.webmanifest"> <link rel='icon' type='image/png' href='view/assets/img/logo.png' /> 
<link rel="stylesheet" href="view/assets/dist/font-awesome/css/all.css"> 
<link rel="stylesheet" href="view/assets/css/main.css"> 
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>
<body>