<div class="body">
    <div class="corpo">
        <div class="acesso-negado-conteiner">
            <span class="acesso-negado"><i class="fas fa-exclamation-circle"></i><h1>Erro 404<h1></span>
        </div>
        <div class="acesso-negado-voltar">
            <form method="Post" action="<?= $GLOBALS['referer'] ?>">
                <span>Deslcupe, mas não conseguimos localizar esta página!</span>
            </form>
        </div>
    </div>
</div>